version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  db:
    image: postgres
    container_name: main_postgres
    restart: always
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - main_postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
  redis:
    image: redis:alpine
    command:
      - redis-server
    ports:
      - "6379:6379"
    container_name: main_Redis
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  main_postgres:
  pgadmin-data:
  redis-data:
  redis-conf:
